# Generated by Django 5.1.7 on 2025-03-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedule',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
