# Generated by Django 5.1.7 on 2025-03-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('homework', models.TextField(blank=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('homework_done', models.BooleanField(default=False)),
                ('homework_sent', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='LessonTopic',
        ),
    ]
